language: php

sudo: false

matrix:
  include:
    - env: DBTYPE=mysql; MW=1.31.6; SMW=3.1.2
      php: 7.2
    - env: DBTYPE=mysql; MW=1.27.0; SMW=2.5.4; TYPE=coverage
      php: 7.0
    - env: DBTYPE=sqlite; MW=1.28.2; SMW=2.5.4
      php: 7.0
    - env: DBTYPE=mysql; MW=1.34.0; SMW=dev-master
      php: 7.4

install:
  - travis_retry composer self-update
  - bash .travis.install.sh

script: ../phase3/tests/phpunit/phpunit.php -c ../phase3/extensions/SemanticWatchlist/phpunit.xml.dist

after_success:
  - if [[ "$TYPE" != "coverage" ]]; then exit 0; fi
  - ../phase3/tests/phpunit/phpunit.php -c ../phase3/extensions/SemanticWatchlist/phpunit.xml.dist --coverage-clover coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $HOME/.composer/cache
